/* white label: City Name */
UILabel *label39 = [[UILabel alloc] initWithFrame:CGRectMake(20.0, 20.0, 114.0, 29.0)];
label39.adjustsFontSizeToFitWidth = YES;
label39.alpha = 1.000;
label39.autoresizesSubviews = YES;
label39.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
label39.baselineAdjustment = UIBaselineAdjustmentAlignCenters;
label39.clearsContextBeforeDrawing = YES;
label39.clipsToBounds = YES;
label39.contentMode = UIViewContentModeLeft;
label39.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
label39.enabled = YES;
//label39.frame = CGRectMake(20.0, 20.0, 114.0, 29.0);
label39.hidden = NO;
label39.highlightedTextColor = [UIColor colorWithWhite:1.000 alpha:1.000];
label39.lineBreakMode = UILineBreakModeTailTruncation;
label39.minimumFontSize = 10.000;
label39.multipleTouchEnabled = NO;
label39.numberOfLines = 1;
label39.opaque = NO;
label39.shadowOffset = CGSizeMake(0.0, -1.0);
label39.tag = 0;
label39.text = @"City Name";
label39.textAlignment = UITextAlignmentLeft;
label39.textColor = [UIColor colorWithWhite:1.000 alpha:1.000];
label39.userInteractionEnabled = NO;

/* white label: date */
UILabel *label40 = [[UILabel alloc] initWithFrame:CGRectMake(187.0, 20.0, 74.0, 21.0)];
label40.adjustsFontSizeToFitWidth = YES;
label40.alpha = 1.000;
label40.autoresizesSubviews = YES;
label40.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
label40.baselineAdjustment = UIBaselineAdjustmentAlignCenters;
label40.clearsContextBeforeDrawing = YES;
label40.clipsToBounds = YES;
label40.contentMode = UIViewContentModeLeft;
label40.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
label40.enabled = YES;
//label40.frame = CGRectMake(187.0, 20.0, 74.0, 21.0);
label40.hidden = NO;
label40.highlightedTextColor = [UIColor colorWithWhite:1.000 alpha:1.000];
label40.lineBreakMode = UILineBreakModeTailTruncation;
label40.minimumFontSize = 10.000;
label40.multipleTouchEnabled = NO;
label40.numberOfLines = 1;
label40.opaque = NO;
label40.shadowOffset = CGSizeMake(0.0, -1.0);
label40.tag = 0;
label40.text = @"0000-00-00";
label40.textAlignment = UITextAlignmentLeft;
label40.textColor = [UIColor colorWithWhite:1.000 alpha:1.000];
label40.userInteractionEnabled = NO;

/* white label: Now */
UILabel *label45 = [[UILabel alloc] initWithFrame:CGRectMake(20.0, 57.0, 143.0, 21.0)];
label45.adjustsFontSizeToFitWidth = YES;
label45.alpha = 1.000;
label45.autoresizesSubviews = YES;
label45.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
label45.baselineAdjustment = UIBaselineAdjustmentAlignCenters;
label45.clearsContextBeforeDrawing = YES;
label45.clipsToBounds = YES;
label45.contentMode = UIViewContentModeLeft;
label45.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
label45.enabled = YES;
//label45.frame = CGRectMake(20.0, 57.0, 143.0, 21.0);
label45.hidden = NO;
label45.highlightedTextColor = [UIColor colorWithWhite:1.000 alpha:1.000];
label45.lineBreakMode = UILineBreakModeTailTruncation;
label45.minimumFontSize = 10.000;
label45.multipleTouchEnabled = NO;
label45.numberOfLines = 1;
label45.opaque = NO;
label45.shadowOffset = CGSizeMake(0.0, -1.0);
label45.tag = 0;
label45.text = @"Now";
label45.textAlignment = UITextAlignmentLeft;
label45.textColor = [UIColor colorWithRed:1.000 green:1.000 blue:1.000 alpha:1.000];
label45.userInteractionEnabled = NO;

/* black label: Temp */
UILabel *label48 = [[UILabel alloc] initWithFrame:CGRectMake(120.0, 78.0, 49.0, 21.0)];
label48.adjustsFontSizeToFitWidth = NO;
label48.alpha = 1.000;
label48.autoresizesSubviews = YES;
label48.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
label48.baselineAdjustment = UIBaselineAdjustmentAlignCenters;
label48.clearsContextBeforeDrawing = YES;
label48.clipsToBounds = YES;
label48.contentMode = UIViewContentModeLeft;
label48.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
label48.enabled = YES;
//label48.frame = CGRectMake(120.0, 78.0, 49.0, 21.0);
label48.hidden = NO;
label48.highlightedTextColor = [UIColor colorWithWhite:1.000 alpha:1.000];
label48.lineBreakMode = UILineBreakModeTailTruncation;
label48.minimumFontSize = 10.000;
label48.multipleTouchEnabled = NO;
label48.numberOfLines = 1;
label48.opaque = NO;
label48.shadowOffset = CGSizeMake(0.0, -1.0);
label48.tag = 0;
label48.text = @"Temp:";
label48.textAlignment = UITextAlignmentLeft;
label48.textColor = [UIColor colorWithRed:0.000 green:0.000 blue:0.000 alpha:1.000];
label48.userInteractionEnabled = NO;

/* black label: 00F (00C) */
UILabel *label51 = [[UILabel alloc] initWithFrame:CGRectMake(200.0, 78.0, 96.0, 21.0)];
label51.adjustsFontSizeToFitWidth = NO;
label51.alpha = 1.000;
label51.autoresizesSubviews = YES;
label51.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
label51.baselineAdjustment = UIBaselineAdjustmentAlignCenters;
label51.clearsContextBeforeDrawing = YES;
label51.clipsToBounds = YES;
label51.contentMode = UIViewContentModeLeft;
label51.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
label51.enabled = YES;
//label51.frame = CGRectMake(200.0, 78.0, 96.0, 21.0);
label51.hidden = NO;
label51.highlightedTextColor = [UIColor colorWithWhite:1.000 alpha:1.000];
label51.lineBreakMode = UILineBreakModeTailTruncation;
label51.minimumFontSize = 10.000;
label51.multipleTouchEnabled = NO;
label51.numberOfLines = 1;
label51.opaque = NO;
label51.shadowOffset = CGSizeMake(0.0, -1.0);
label51.tag = 0;
label51.text = @"00F (00C)";
label51.textAlignment = UITextAlignmentLeft;
label51.textColor = [UIColor colorWithRed:0.000 green:0.000 blue:0.000 alpha:1.000];
label51.userInteractionEnabled = NO;


/* black label: Humidity */
UILabel *label53 = [[UILabel alloc] initWithFrame:CGRectMake(121.0, 102.0, 180.0, 21.0)];
label53.adjustsFontSizeToFitWidth = NO;
label53.alpha = 1.000;
label53.autoresizesSubviews = YES;
label53.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
label53.baselineAdjustment = UIBaselineAdjustmentAlignCenters;
label53.clearsContextBeforeDrawing = YES;
label53.clipsToBounds = YES;
label53.contentMode = UIViewContentModeLeft;
label53.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
label53.enabled = YES;
//label53.frame = CGRectMake(121.0, 102.0, 180.0, 21.0);
label53.hidden = NO;
label53.highlightedTextColor = [UIColor colorWithWhite:1.000 alpha:1.000];
label53.lineBreakMode = UILineBreakModeTailTruncation;
label53.minimumFontSize = 10.000;
label53.multipleTouchEnabled = NO;
label53.numberOfLines = 1;
label53.opaque = NO;
label53.shadowOffset = CGSizeMake(0.0, -1.0);
label53.tag = 0;
label53.text = @"Humidity 000";
label53.textAlignment = UITextAlignmentLeft;
label53.textColor = [UIColor colorWithRed:0.000 green:0.000 blue:0.000 alpha:1.000];
label53.userInteractionEnabled = NO;

/* black label: Wind speed mph */
UILabel *label55 = [[UILabel alloc] initWithFrame:CGRectMake(121.0, 124.0, 192.0, 21.0)];
label55.adjustsFontSizeToFitWidth = NO;
label55.alpha = 1.000;
label55.autoresizesSubviews = YES;
label55.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
label55.baselineAdjustment = UIBaselineAdjustmentAlignCenters;
label55.clearsContextBeforeDrawing = YES;
label55.clipsToBounds = YES;
label55.contentMode = UIViewContentModeLeft;
label55.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
label55.enabled = YES;
//label55.frame = CGRectMake(121.0, 124.0, 192.0, 21.0);
label55.hidden = NO;
label55.highlightedTextColor = [UIColor colorWithWhite:1.000 alpha:1.000];
label55.lineBreakMode = UILineBreakModeTailTruncation;
label55.minimumFontSize = 10.000;
label55.multipleTouchEnabled = NO;
label55.numberOfLines = 1;
label55.opaque = NO;
label55.shadowOffset = CGSizeMake(0.0, -1.0);
label55.tag = 0;
label55.text = @"W at 000mph";
label55.textAlignment = UITextAlignmentLeft;
label55.textColor = [UIColor colorWithRed:0.000 green:0.000 blue:0.000 alpha:1.000];
label55.userInteractionEnabled = NO;


/* black label: Current condition string */
UILabel *label57 = [[UILabel alloc] initWithFrame:CGRectMake(120.0, 146.0, 139.0, 21.0)];
label57.adjustsFontSizeToFitWidth = NO;
label57.alpha = 1.000;
label57.autoresizesSubviews = YES;
label57.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
label57.baselineAdjustment = UIBaselineAdjustmentAlignCenters;
label57.clearsContextBeforeDrawing = YES;
label57.clipsToBounds = YES;
label57.contentMode = UIViewContentModeLeft;
label57.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
label57.enabled = YES;
//label57.frame = CGRectMake(120.0, 146.0, 139.0, 21.0);
label57.hidden = NO;
label57.highlightedTextColor = [UIColor colorWithWhite:1.000 alpha:1.000];
label57.lineBreakMode = UILineBreakModeTailTruncation;
label57.minimumFontSize = 10.000;
label57.multipleTouchEnabled = NO;
label57.numberOfLines = 1;
label57.opaque = NO;
label57.shadowOffset = CGSizeMake(0.0, -1.0);
label57.tag = 0;
label57.text = @"Currently Foo";
label57.textAlignment = UITextAlignmentLeft;
label57.textColor = [UIColor colorWithRed:0.000 green:0.000 blue:0.000 alpha:1.000];
label57.userInteractionEnabled = NO;


/* Info button */
UIButton *button36 = [UIButton buttonWithType:UIButtonTypeInfoLight];
button36.adjustsImageWhenDisabled = YES;
button36.adjustsImageWhenHighlighted = YES;
button36.alpha = 1.000;
button36.autoresizesSubviews = YES;
button36.autoresizingMask = UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleTopMargin;
button36.clearsContextBeforeDrawing = NO;
button36.clipsToBounds = NO;
button36.contentHorizontalAlignment = UIControlContentHorizontalAlignmentCenter;
button36.contentMode = UIViewContentModeScaleToFill;
button36.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
button36.contentVerticalAlignment = UIControlContentVerticalAlignmentCenter;
button36.enabled = YES;
button36.frame = CGRectMake(289.0, 431.0, 18.0, 19.0);
button36.hidden = NO;
button36.highlighted = NO;
button36.multipleTouchEnabled = NO;
button36.opaque = NO;
button36.reversesTitleShadowWhenHighlighted = NO;
button36.selected = NO;
button36.showsTouchWhenHighlighted = YES;
button36.tag = 0;
button36.titleLabel.lineBreakMode = UILineBreakModeMiddleTruncation;
button36.titleLabel.shadowOffset = CGSizeMake(0.0, 0.0);
button36.userInteractionEnabled = YES;
[button36 setTitleColor:[UIColor colorWithRed:0.196 green:0.310 blue:0.522 alpha:1.000] forState:UIControlStateNormal];
[button36 setTitleColor:[UIColor colorWithRed:1.000 green:1.000 blue:1.000 alpha:1.000] forState:UIControlStateHighlighted];
[button36 setTitleShadowColor:[UIColor colorWithWhite:0.000 alpha:1.000] forState:UIControlStateNormal];

/* Activity Indicator */
UIActivityIndicatorView *activityindicatorview96 = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleWhite];
activityindicatorview96.alpha = 1.000;
activityindicatorview96.autoresizesSubviews = YES;
activityindicatorview96.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
activityindicatorview96.clearsContextBeforeDrawing = YES;
activityindicatorview96.clipsToBounds = NO;
activityindicatorview96.contentMode = UIViewContentModeScaleToFill;
activityindicatorview96.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
activityindicatorview96.frame = CGRectMake(282.0, 9.0, 20.0, 20.0);
activityindicatorview96.hidden = YES;
activityindicatorview96.hidesWhenStopped = YES;
activityindicatorview96.multipleTouchEnabled = NO;
activityindicatorview96.opaque = NO;
activityindicatorview96.tag = 0;
activityindicatorview96.userInteractionEnabled = YES;
[activityindicatorview96 stopAnimating];

UIImageView *imageview121 = [[UIImageView alloc] initWithFrame:CGRectMake(9.0, 91.0, 64.0, 64.0)];
imageview121.alpha = 1.000;
imageview121.autoresizesSubviews = YES;
imageview121.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
imageview121.clearsContextBeforeDrawing = YES;
imageview121.clipsToBounds = NO;
imageview121.contentMode = UIViewContentModeScaleToFill;
imageview121.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
//imageview121.frame = CGRectMake(9.0, 91.0, 64.0, 64.0);
imageview121.hidden = NO;
imageview121.highlighted = NO;
imageview121.multipleTouchEnabled = NO;
imageview121.opaque = YES;
imageview121.tag = 0;
imageview121.userInteractionEnabled = NO;

UITableView *tableview102 = [[UITableView alloc] initWithFrame:CGRectMake(0.0, 175.0, 320.0, 254.0) style:UITableViewStylePlain];
tableview102.allowsMultipleSelection = NO;
tableview102.allowsMultipleSelectionDuringEditing = NO;
tableview102.allowsSelection = NO;
tableview102.allowsSelectionDuringEditing = NO;
tableview102.alpha = 1.000;
tableview102.alwaysBounceHorizontal = NO;
tableview102.alwaysBounceVertical = YES;
tableview102.autoresizesSubviews = YES;
tableview102.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
tableview102.backgroundColor = [UIColor colorWithWhite:1.000 alpha:1.000];
tableview102.bounces = YES;
tableview102.bouncesZoom = YES;
tableview102.canCancelContentTouches = YES;
tableview102.clearsContextBeforeDrawing = YES;
tableview102.clipsToBounds = YES;
tableview102.contentMode = UIViewContentModeScaleToFill;
tableview102.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
tableview102.delaysContentTouches = YES;
tableview102.directionalLockEnabled = NO;
//tableview102.frame = CGRectMake(0.0, 175.0, 320.0, 254.0);
tableview102.hidden = NO;
tableview102.indicatorStyle = UIScrollViewIndicatorStyleDefault;
tableview102.maximumZoomScale = 1.000;
tableview102.minimumZoomScale = 1.000;
tableview102.multipleTouchEnabled = NO;
tableview102.opaque = YES;
tableview102.pagingEnabled = NO;
tableview102.rowHeight = 64;
tableview102.scrollEnabled = YES;
tableview102.sectionFooterHeight = 22;
tableview102.sectionHeaderHeight = 22;
tableview102.sectionIndexMinimumDisplayRowCount = 0;
tableview102.separatorStyle = UITableViewCellSeparatorStyleSingleLine;
tableview102.showsHorizontalScrollIndicator = NO;
tableview102.showsVerticalScrollIndicator = YES;
tableview102.tag = 0;
tableview102.userInteractionEnabled = YES;

UIView *view34 = [[UIView alloc] initWithFrame:CGRectMake(0.0, 20.0, 320.0, 460.0)];
view34.alpha = 1.000;
view34.autoresizesSubviews = YES;
view34.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
view34.backgroundColor = [UIColor colorWithWhite:0.250 alpha:1.000];
view34.clearsContextBeforeDrawing = NO;
view34.clipsToBounds = NO;
view34.contentMode = UIViewContentModeScaleToFill;
view34.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
//view34.frame = CGRectMake(0.0, 20.0, 320.0, 460.0);
view34.hidden = NO;
view34.multipleTouchEnabled = NO;
view34.opaque = YES;
view34.tag = 0;
view34.userInteractionEnabled = YES;
[view34 addSubview:label39];
[view34 addSubview:button36];
[view34 addSubview:tableview102];
[view34 addSubview:label40];
[view34 addSubview:label45];
[view34 addSubview:label48];
[view34 addSubview:label51];
[view34 addSubview:label53];
[view34 addSubview:label55];
[view34 addSubview:label57];
[view34 addSubview:imageview121];
[view34 addSubview:activityindicatorview96];

MainViewController *inviewcontroller1 = [[NSProxy alloc] init];

UIResponder *responder2 = [[NSProxy alloc] init];
